spring:
  application:
    name: Prenotazione Postazioni
  datasource:
    url: jdbc:postgresql://localhost:5432/prenotazione
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 600000
      minimum-idle: 10
      maximum-pool-size: 30
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
 
server:
  port: 9890
 
springdoc:
  api-docs:
    path: /v1/api-docs        
  swagger-ui:
    path: /v1/api-list.html
    operationsSorter: method
